workspace:
  base: /go

pipeline:
  build:
    image: golang:1.6
    commands:
      - CGO_ENABLED=0 go build

  docker:
    storage_driver: overlay
    repo: plugins/swift
    tag: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Swift
  desc: Publish files and artifacts to OpenStack Swift
  type: publish
  image: plugins/swift
  labels:
    - publish
    - artifacts
    - openstack
    - swift
